server:
  port: 8080
  context-path: /
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loatr?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ud!qXi5mGc,d
    driverClassName: com.mysql.cj.jdbc.Driver